"injector":
  "resources":
    "limits":
      "cpu": "100m"
      "memory": "200Mi"
    "requests":
      "cpu": "10m"
      "memory": "20Mi"
"server":
  "ingress":
    "annotations":
      "traefik.ingress.kubernetes.io/router.middlewares": "traefik-forward-auth-traefik-forward-auth@kubernetescrd"
    "enabled": true
    "hosts":
    - "host": "vault.khand.dev"
    "ingressClassName": "traefik"
  "resources":
    "limits":
      "cpu": "200m"
      "memory": "200Mi"
    "requests":
      "cpu": "60m"
      "memory": "62.7Mi"
