apiVersion: "external-secrets.io/v1alpha1"
kind: "ExternalSecret"
metadata:
  name: "cloudflare-api"
  namespace: "ddclient"
spec:
  refreshInterval: "15s"
  target: {}
  secretStoreRef:
    name: "vault-backend"
    kind: "ClusterSecretStore"
  data:
    - secretKey: "token"
      remoteRef:
        key: "cloudflare"
        property: "global-api-token"
    - secretKey: "email"
      remoteRef:
        key: "cloudflare"
        property: "email"
