apiVersion: "external-secrets.io/v1alpha1"
kind: "ExternalSecret"
metadata:
  name: "google-oauth-client"
  namespace: "traefik-forward-auth"
spec: 
  refreshInterval: "15s"
  target: {}
  secretStoreRef:
    name: "vault-backend"
    kind: "ClusterSecretStore"
  data:
    - secretKey: "id"
      remoteRef:
        key: "google-oauth-client"
        property: "id"
    - secretKey: "secret"
      remoteRef:
        key: "google-oauth-client"
        property: "secret"
---
apiVersion: "external-secrets.io/v1alpha1"
kind: "ExternalSecret"
metadata:
  name: "forward-auth-key"
  namespace: "traefik-forward-auth"
spec:
  refreshInterval: "15s"
  target: {}
  secretStoreRef:
    name: "vault-backend"
    kind: "ClusterSecretStore"
  data:
    - secretKey: "secret"
      remoteRef:
        key: "forward-auth-key"
        property: "secret"
