apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-forward-auth
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://k8s-at-home.com/charts/
    chart: traefik-forward-auth
    targetRevision: "1.0.10"
    helm:
      values: |
        middleware:
          enabled: true
        providers:
          google: 
            enabled: true
        restrictions:
          domain: "khand.dev"
          whitelist: "rkeithhand@gmail.com"
        secret: "-"
        env:
          - name: "PROVIDERS_GOOGLE_CLIENT_ID"
            valueFrom:
              secretKeyRef:
                name: "google-oauth-client"
                key: "id"
          - name: "PROVIDERS_GOOGLE_CLIENT_SECRET"
            valueFrom:
              secretKeyRef:
                name: "google-oauth-client"
                key: "secret"
          - name: "MATCH_WHITELIST_OR_DOMAIN"
            value: "true"
          - name: "SECRET"
            valueFrom:
              secretKeyRef:
                name: "forward-auth-key"
                key: "secret"
  destination:
    namespace: traefik-forward-auth
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
