apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: game-servers
  namespace: argocd
spec:
  sourceRepos:
    - '*'
  destinations:
    - server: 'https://kubernetes.default.svc'
      namespace: 'games-*'
  # roles:
