"server":
  "ingress":
    "annotations":
      "traefik.ingress.kubernetes.io/router.middlewares": "traefik-forward-auth-traefik-forward-auth@kubernetescrd"
    "enabled": true
    "hosts":
    - "host": "vault.khand.dev"
    "ingressClassName": "traefik"
