"server":
  "extraArgs":
  - "--insecure"
  "ingress":
    "annotations":
      "traefik.ingress.kubernetes.io/router.middlewares": "traefik-forward-auth-traefik-forward-auth@kubernetescrd"
    "enabled": true
    "hosts":
    - "argo.khand.dev"
